<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AssemblyName>FFXIII2SaveEditor</AssemblyName>
    <RootNamespace>FFXIII2SaveEditor</RootNamespace>
    <Version>1.9.33</Version>
    <AssemblyVersion>1.9.33.0</AssemblyVersion>
    <FileVersion>1.9.33.0</FileVersion>
<Platforms>AnyCPU;x64</Platforms>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
